const importNames = [
  ['/img/skills/aws.svg', 'Amazon Web Services', 'Amazon Web Services'],
  ['/img/skills/bash.svg', 'Bash', 'Bash'],
  ['/img/skills/csharp.svg', 'C#', 'C#'],
  ['/img/skills/css3.svg', 'CSS3', 'CSS3'],
  ['/img/skills/docker.svg', 'Docker', 'Docker'],
  ['/img/skills/git.svg', 'Git & Github', 'Git and Github'],
  ['/img/skills/gql.svg', 'GraphQL', 'GraphQL'],
  ['/img/skills/html.svg', 'HTML5', 'HTML5'],
  ['/img/skills/java.svg', 'JAVA', 'JAVA'],
  ['/img/skills/javascript.svg', 'JavaScript', 'JavaScript'],
  ['/img/skills/laravel.svg', 'Laravel', 'Laravel'],
  ['/img/skills/linux.svg', 'Linux Servers', 'Linux Servers'],
  ['/img/skills/netcore.svg', '.Net Core', '.Net Core'],
  ['/img/skills/nextjs.svg', 'NextJS', 'NextJS'],
  ['/img/skills/nodejs.svg', 'NodeJS & Express', 'NodeJS and Express'],
  ['/img/skills/php.svg', 'PHP', 'PHP'],
  ['/img/skills/python.svg', 'Python', 'Python'],
  ['/img/skills/reactjs.svg', 'ReactJS', 'ReactJS'],
  ['/img/skills/reactnative.svg', 'React-Native', 'React-Native'],
  ['/img/skills/redux.svg', 'Redux', 'Redux'],
  ['/img/skills/spring.svg', 'Java Spring', 'Java Spring'],
  ['/img/skills/sql.svg', 'SQL', 'SQL'],
  ['/img/skills/vuejs.svg', 'VueJS', 'VueJS'],
  ['/img/skills/webpack.svg', 'Webpack & Babel', 'Webpack and Babel'],
  ['/img/skills/woocommerce.svg', 'WooCommerce', 'WooCommerce'],
];

export default importNames;
